#!/bin/bash
# echo " Installing rpm for jde9.1"

yum  install  binutils* -y --skip-broken
yum  install  compat-libstdc++-33* -y  --skip-broken
yum  install  elfutils-libelf-devel* -y --skip-broken
yum  install  gcc* -y --skip-broken
yum  install  gcc-c++* -y --skip-broken
yum  install  glibc* -y --skip-broken
yum  install  glibc-devel* -y --skip-broken
yum  install  libaio* -y --skip-broken
yum  install  libaio-devel* -y --skip-broken
yum  install  libgcc* -y --skip-broken
yum  install  libstdc++* -y --skip-broken
yum  install  libstdc++-devel* -y --skip-broken
yum  install  libX11* -y --skip-broken
yum  install  libXau* -y --skip-broken
yum  install  libxcb* -y --skip-broken
yum  install  libXext* -y --skip-broken
yum  install  libXi* -y --skip-broken
yum  install  libXtst* -y --skip-broken
yum  install  make* -y --skip-broken
yum  install  sysstat* ---skip-broken
yum  install  unixODBC* -y --skip-broken
yum  install  unixODBC-devel* -y --skip-broken
yum  install  zlib-devel* -y --skip-broken
yum  install  ncompress* -y --skip-broken
yum  install  ksh* -y --skip-broken
yum  install  compat-libstdc++* -y --skip-broken
yum  install  compat-libstdc++-33* -y --skip-broken
yum  install  glibc* -y --skip-broken
yum  install  glibc-devel* -y --skip-broken
yum  install  libaio* -y --skip-broken
yum  install  libaio-devel* -y --skip-broken
yum  install  libgcc* -y --skip-broken
yum  install  libstdc++* -y --skip-broken
yum  install  libstdc++-devel* -y --skip-broken
yum  install  libX11* -y --skip-broken
yum  install  libXau* -y --skip-broken
yum  install  libxcb* -y --skip-broken
yum  install  libXext* -y --skip-broken
yum  install  libXi* -y --skip-broken
yum  install  libXtst* -y --skip-broken
yum  install  nss-softokn-freebl* -y --skip-broken
yum  install  zlib* -y --skip-broken
yum  install  zlib-devel* -y --skip-broken
yum   install  compat-libstdc++-296.i686 -y --skip-broken
yum   install  compat-libstdc++-33.i686 -y --skip-broken
yum   install  glibc.i686 -y --skip-broken
yum   install  glibc-devel.i686 -y --skip-broken
yum   install  glibc-devel.i686 -y --skip-broken
yum   install  libaio.i686 -y --skip-broken
yum   install  libaio-devel.i686 -y --skip-broken
yum   install  libaio-devel.i686 -y --skip-broken
yum   install  libgcc.i686  -y --skip-broken
yum   install  libstdc++.i686 -y --skip-broken
yum   install  libstdc++-devel.i686 -y --skip-broken
yum   install  libstdc++-static.i686 -y --skip-broken
yum   install  libstdc++-devel.i686 -y --skip-broken
yum   install  libX11.i686 -y --skip-broken
yum   install  libX11-devel.i686 -y --skip-broken
yum   install  libXau.i686 -y --skip-broken
yum   install  libXau-devel.i686 -y --skip-broken
yum   install  libxcb.i686 -y --skip-broken
yum   install  libxcb-devel.i686 -y --skip-broken
yum   install  libXext.i686 -y --skip-broken
yum   install  libXext-devel.i686 -y --skip-broken
yum   install  libXi.i686 -y --skip-broken
yum   install  libXi-devel.i686 -y --skip-broken
yum   install  libXinerama.i686 -y --skip-broken
yum   install  libXinerama-devel.i686 -y --skip-broken
yum   install  libXtst.i686 -y --skip-broken
yum   install  libXtst-devel.i686 -y --skip-broken
yum   install  nss-softokn-freebl.i686 -y --skip-broken
yum   install  nss-softokn-freebl-devel.i686 -y --skip-broken
yum   install  zlib.i686 -y --skip-broken
yum   install  zlib-devel.i686 -y --skip-broken
yum   install  zlib-static.i686 -y --skip-broken
